/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CiscoGT;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.net.URI;
import java.util.*;
import java_cup.runtime.Symbol;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Carlos Bautista
 */
public class InterfazSintax extends javax.swing.JFrame {
    
    FondoPanel fondo= new FondoPanel();
    /**
     * Creates new form InterfazSintax
     */
    public InterfazSintax() 
    {
        initComponents();
        
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public Image getIconImage() 
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/Imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        botonabrir = new javax.swing.JButton();
        botonanalizar = new javax.swing.JButton();
        botoncortar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        botonanalizar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonWeb1 = new CiscoGT.BotonWeb();
        botonWeb2 = new CiscoGT.BotonWeb();
        botonWeb3 = new CiscoGT.BotonWeb();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CompilerGT - UPANA Barillas");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 244));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 270, 244));

        botonabrir.setBackground(new java.awt.Color(255, 255, 255));
        botonabrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/open-file_40455.png"))); // NOI18N
        botonabrir.setContentAreaFilled(false);
        botonabrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonabrirActionPerformed(evt);
            }
        });
        getContentPane().add(botonabrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 50));

        botonanalizar.setBackground(new java.awt.Color(255, 255, 255));
        botonanalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Analizar3.png"))); // NOI18N
        botonanalizar.setContentAreaFilled(false);
        botonanalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonanalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonanalizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonanalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 70, 50));

        botoncortar.setBackground(new java.awt.Color(255, 255, 255));
        botoncortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Basura1.png"))); // NOI18N
        botoncortar.setContentAreaFilled(false);
        botoncortar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoncortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncortarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncortar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 70, 50));

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 238, 4));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPILADOR C ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 270, 240));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Limpiar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 70, -1));

        botonanalizar2.setBackground(new java.awt.Color(255, 255, 255));
        botonanalizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Analizar4.png"))); // NOI18N
        botonanalizar2.setContentAreaFilled(false);
        botonanalizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonanalizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonanalizar2ActionPerformed(evt);
            }
        });
        getContentPane().add(botonanalizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 70, 50));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Analizador  Sintáctico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 270, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Analizador Lexicográfico");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 270, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menú de Operaciones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 370, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Abrir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 60, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lexic");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 70, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sintactic");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 90, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logocisco-splash.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 90));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Anime Ace 2.0 BB", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2,020");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Anime Ace 2.0 BB", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cisco GT ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        botonWeb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/instagam_109863.png"))); // NOI18N
        botonWeb1.setLink("https://www.instagram.com/3l_1ng3/");
        getContentPane().add(botonWeb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, -1));

        botonWeb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/youtube_109860.png"))); // NOI18N
        botonWeb2.setLink("https://www.youtube.com/c/CiscoGT");
        getContentPane().add(botonWeb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        botonWeb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/_twitter_icon-icons.com_65787.png"))); // NOI18N
        botonWeb3.setLink("https://twitter.com/cisco_502");
        getContentPane().add(botonWeb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel13.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Carlos Bautista - CiscoGT - Todos los derechos reservados");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 476, 890, 30));

        setBounds(0, 0, 900, 552);
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonabrirActionPerformed
        // TODO add your handling code here:
         int iResp;
        String strTexto= null;
        ArrayList<String> alLinea=null;
        FileExplorer fmLeeArchivo=null;
        
        try
        {
            iResp=jFileChooser1.showOpenDialog(this);
            if (iResp==jFileChooser1.APPROVE_OPTION) {
                
                fmLeeArchivo = new FileExplorer();
                alLinea=fmLeeArchivo.leeArchivo(jFileChooser1.getSelectedFile().toString());
                if (alLinea.size()>0) {
                    
                    for (int i = 0; i < alLinea.size(); i++) {
                        
                        strTexto=(String)alLinea.get(i);
                        jTextArea1.append(strTexto+ "\n");
                        
                    }
                    
                }
               
                
            }
            
        }catch (Exception ex) 
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botonabrirActionPerformed

    private void botoncortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncortarActionPerformed
        // TODO add your handling code here:
        
        //codigo para limpiar area 1
        jTextArea1.setText(" ");
        //codigo para limpiar area 2
        jTextArea2.setText(" ");
        //codigo para limpiar area 3
        jTextArea3.setText(" ");
    }//GEN-LAST:event_botoncortarActionPerformed

    private void botonanalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonanalizarActionPerformed
        // TODO add your handling code here:
        
        try
        {

            probarLexer();
        }
        catch(IOException ex)
        {
            System.out.println(ex.getMessage());
                    
        }
    }//GEN-LAST:event_botonanalizarActionPerformed

    private void botonanalizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonanalizar2ActionPerformed
        // TODO add your handling code here:
        
        String ST = jTextArea1.getText();
        Sintax s = new Sintax(new CiscoGT.LexerCup(new StringReader(ST)));
        
        try 
        {
            s.parse();
            jTextArea3.setText("Analisis realizado correctamente");
            jTextArea3.setForeground(new Color(25, 111, 61));
        } 
        catch (Exception ex) 
        {
            Symbol sym = s.getS();
            jTextArea3.setText("Error de sintaxis. Linea: " + (sym.right + 1) + " Columna: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
            jTextArea3.setForeground(Color.red);
        }
    }//GEN-LAST:event_botonanalizar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSintax().setVisible(true);
            }
        });
    }
    
    //--------- Para probar nuestro analizador Lexico--------------------------
    public void probarLexer() throws IOException
    {
        InfoAdicional c= new InfoAdicional();
        
        File fichero = new File("fichero.txt");
        PrintWriter Writer;
        
        try 
        {
            Writer = new PrintWriter(fichero);
               Writer.print(jTextArea1.getText());
                  Writer.close();
            
        } 
        
        catch(FileNotFoundException ex)
        {
           // Logger.getLogger(InterfazSintax.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        
        Reader reader;
        reader = new BufferedReader(new FileReader("fichero.txt"));
        LexerFlex lexer = new LexerFlex(reader);
        
        String Resultado="";
        
        while(true)
        {
            Tokens tok= lexer.yylex();
            
            if (tok == null) 
            {
                
                Resultado = Resultado+"FIN";
                jTextArea2.setText(Resultado);
                return ;
            }
            
            switch(tok)
            {
                case ERROR:
                    Resultado = Resultado+"ERROR LEXICO: "+lexer.lexeme+" "+" "+" Linea: "
                            + c.linea+"\n";
                    break;
                case Identificador: case Numero:
                    Resultado = Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
                    break;
                default: 
                    Resultado = Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
                    break;
            }
                    
        } 
    }
    //---------------------------------------------------------------------------------
    
    
    //--------------------Para fondo del panel --------------------------------------------
    class FondoPanel extends JPanel
        {
            private Image imagen;
            
                public void paint (Graphics g)
                {
                    imagen = new ImageIcon(getClass().getResource("/Imagenes/22293.jpg")).getImage();
                    
                    g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
                    
                    setOpaque(false);
                    
                    super.paint(g);
                    
                }
        }
    //-------------------------------------------------------------------------------------
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CiscoGT.BotonWeb botonWeb1;
    private CiscoGT.BotonWeb botonWeb2;
    private CiscoGT.BotonWeb botonWeb3;
    private javax.swing.JButton botonabrir;
    private javax.swing.JButton botonanalizar;
    private javax.swing.JButton botonanalizar2;
    private javax.swing.JButton botoncortar;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
